### ISSUE TITLE
kinect_aux under fuerte

### ISSUE THREAD

**Issue by mayrjohannes** [muhrix/kinect_aux#1]
Hello, in the past it was not a problem to run kinect_aux in fuerte but now after the updates for groovy it seems that I can't use kinect_aux anymore for fuerte. I can't either install it with apt-get nor check it out from the rops and build it by myself because it's now catkinized.
Are there any plans to make it again available for fuerte?

**Comment by muhrix** [comment]
@mayrjohannes With the release of ROS Hydro, the support for Fuerte was officially dropped. Therefore, there are no plans (from my part) to revert kinect_aux back to rosbuild (and I would not be able to test on Fuerte, since I only have Groovy and Hydro installed).
Up until Fuerte, kinect_aux was a package in the kinect stack (rather than a standalone package). I know the kinect_aux from Electric works just fine in Fuerte (I have used it in the past). You can clone the kinect stack repo from github and use kinect_aux with no problems. See https://github.com/ros-pkg-git/kinect. If that does not suit you, let me know and I can guide you through reverting the package back to rosbuild.
